export default {
	"pages": {
		"root": {
			"name": "root",
			"children": [
				"682f25d09335410018cc8551",
				"682f25d09335410018cc8555",
				"683d651e9710450018a9407d",
				"6845785dcafddc001873ab8d",
				"6846a848061617001efe842c"
			],
			"id": "root",
			"pageUrl": "root"
		},
		"682f25d09335410018cc8551": {
			"id": "682f25d09335410018cc8551",
			"name": "404",
			"pageUrl": "404",
			"seo": {
				"title": ""
			}
		},
		"682f25d09335410018cc8555": {
			"id": "682f25d09335410018cc8555",
			"name": "SEARCH",
			"pageUrl": "index",
			"seo": {
				"og:description": "Trouve des sons d’artistes émergents selon ton humeur et collectionne les cartes numériques des meilleurs morceaux.",
				"title": "Home | Recherche par mood",
				"og:title": "Découvre les morceaux qui matchent ton mood – Trackdiggers",
				"og:image": "https://uploads.quarkly.io/682f25cf9335410018cc8538/images/Copie%20de%20TrackDigger%20%2864%20x%2064%20px%29.png?v=2025-06-21T16:50:26.362Z",
				"description": "Trackdiggers te propose des sons d’artistes émergents en fonction de ton humeur. Trouve les morceaux qui matchent ton mood, découvre, vote et collectionne des cartes digitales exclusives."
			},
			"styles": {
				"font": "1em --fontFamily-sansVerdana"
			}
		},
		"683d651e9710450018a9407d": {
			"id": "683d651e9710450018a9407d",
			"pageUrl": "votes",
			"name": "VOTES",
			"seo": {
				"title": "Vote pour les meilleurs sons – Trackdiggers",
				"description": "Découvre les morceaux proposés par la communauté Trackdiggers et vote pour ceux qui méritent leur carte collector. Chaque vote influence les prochaines sélections musicales.",
				"og:title": "Vote pour les futurs morceaux collector – Trackdiggers",
				"og:description": "Exprime ton avis musical en votant pour les sons proposés par la communauté. Les morceaux les plus votés reçoivent une carte unique.",
				"og:image": "https://uploads.quarkly.io/682f25cf9335410018cc8538/images/Copie%20de%20TrackDigger%20%2864%20x%2064%20px%29.png?v=2025-06-21T16:50:26.362Z"
			}
		},
		"6845785dcafddc001873ab8d": {
			"pageUrl": "cartes",
			"id": "6845785dcafddc001873ab8d",
			"name": "CARTES",
			"seo": {
				"title": "Cartes musicales Trackdiggers – Collectionne tes sons préférés",
				"description": "Découvre ta collection de cartes musicales uniques sur Trackdiggers. Chaque carte est liée à un morceau sélectionné par la communauté et numérotée pour être exclusive.",
				"og:title": "Collectionne des cartes musicales exclusives – Trackdiggers",
				"og:description": "Trackdiggers transforme les sons en cartes uniques. Garde, partage ou admire ta collection de morceaux sélectionnés par la communauté.",
				"og:image": "https://uploads.quarkly.io/682f25cf9335410018cc8538/images/Copie%20de%20TrackDigger%20%2864%20x%2064%20px%29.png?v=2025-06-21T16:50:26.362Z"
			}
		},
		"6846a848061617001efe842c": {
			"id": "6846a848061617001efe842c",
			"pageUrl": "informations-legales",
			"name": "Informations légales"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"robotsFileType": "autogenerated",
			"favicon_32px": "https://uploads.quarkly.io/682f25cf9335410018cc8538/images/Copie%20de%20TrackDigger%20%2864%20x%2064%20px%29.png?v=2025-06-21T16:50:26.362Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/682f25cf9335410018cc8538/images/Copie%20de%20TrackDigger%20%2864%20x%2064%20px%29.png?v=2025-06-21T16:50:26.362Z",
			"title": "Trackdiggers – Découvre, vote, collectionne les sons",
			"description": "Découvre de nouveaux morceaux selon ton mood, vote pour les meilleurs sons et reçois des cartes musicales collector, uniques.",
			"og:title": "Trackdiggers – Cartes collector et sons émergents",
			"og:image": "https://uploads.quarkly.io/682f25cf9335410018cc8538/images/Copie%20de%20TrackDigger.svg?v=2025-06-21T15:50:41.804Z",
			"og:description": "Choisis ton mood et découvre les morceaux qui matchent. Vote pour tes coups de cœur et collectionne des cartes numériques uniques.",
			"favicon_win10_270px": "https://uploads.quarkly.io/682f25cf9335410018cc8538/images/Copie%20de%20TrackDigger%20%2864%20x%2064%20px%29.png?v=2025-06-21T16:50:26.362Z",
			"background_win10": "#000000"
		}
	}
}